version: 2.1

commands:
  print_pipeline_id:
    description: prints the circleci workflow id
    steps:
      - run:
          name: Echo Pipeline Workflow ID
          command: echo workflow id - $CIRCLE_WORKFLOW_ID

jobs:
  print-hello:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Echo Hello
          command: echo hello

  print-world:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Echo World
          command: echo world

  print-env:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Echo Env
          command: echo $MY_NAME

  save_hello_world_workspace:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Save Hello Output
          command: |
            mkdir workspace
            echo hello world > workspace/output.txt
      - persist_to_workspace:
          root: ./workspace
          paths:
            - ./*

  print_hello_world_workspace:
    docker:
      - image: cimg/base:2021.11
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          name: Echo Workspace File
          command: |
            cat ./workspace/output.txt

  save_hello_world_cache:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Save Hello Output
          command: |
            pwd
            echo hello world > ./output.txt
            ls -lah
      - save_cache:
          name: Saving Files to Cache
          key: cache-key-{{ .BuildNum }}
          paths:
            - ./output.txt

  print_hello_world_cache:
    docker:
      - image: cimg/base:2021.11
    steps:
      - restore_cache:
          name: Restore Cache
          key: cache-key
      - run:
          name: Echo Workspace File
          command: |
            pwd
            ls -lah
            cat ./output.txt

  print_workflow_id:
    docker:
      - image: cimg/base:2021.11
    steps:
      - print_pipeline_id

  failing_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Cause Job Failure
          command: exit 1
      - run:
          name: Failed Job Listener
          command: echo Job has failed
          when: on_fail

workflows:
  hello-world-workflow:
    jobs:
      # - print-hello
      # - print-world:
      #     requires:
      #       - print-hello
      # - print-env
      # - save_hello_world_cache
      # - print_hello_world_cache:
      #     requires:
      #       - save_hello_world_cache
      # - print_workflow
      # - failing_job
      - save_hello_world_cache
      - print_hello_world_cache:
          requires:
            - save_hello_world_cache
