version: 2.1

jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Echo Hello"
          commmand: "echo hello"

  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Echo World"
          commmand: "echo world"

workflows:
  hello-world-workflow:
    jobs:
      - print-hello
      - print-world:
          requires: [print-hello]
