version: 2.1

jobs:
  print-hello:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Echo Hello
          command: echo hello

  print-world:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Echo World
          command: echo world

  print-env:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Echo Env
          command: echo $MY_NAME

  save_hello_world_output:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Save Hello Output
          command: |
            pwd
            mkdir workspace
            ls -lah
            echo hello world > workspace/output.txt
      - persist_to_workspace:
          root: ./workspace
          paths:
            - *

  print_output_file:
    docker:
      - image: cimg/base:2021.11
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          name: Echo Workspace File
          command: |
            ls -lah
            ls -lah ./workspace
            cat ./workspace/output.txt

workflows:
  hello-world-workflow:
    jobs:
      # - print-hello
      # - print-world:
      #     requires:
      #       - print-hello
      # - print-env
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
