version: 2.1

commands:
  print_pipeline_id:
    description: prints the circleci workflow id
    steps:
      - run:
          name: Echo Pipeline Workflow ID
          command: echo workflow id - $CIRCLE_WORKFLOW_ID

jobs:
  print-hello:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Echo Hello
          command: echo hello

  print-world:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Echo World
          command: echo world

  print-env:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Echo Env
          command: echo $MY_NAME

  save_hello_world_output:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Save Hello Output
          command: |
            mkdir workspace
            echo hello world > workspace/output.txt
      - persist_to_workspace:
          root: ./workspace
          paths:
            - ./*

  print_output_file:
    docker:
      - image: cimg/base:2021.11
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          name: Echo Workspace File
          command: |
            cat ./workspace/output.txt

  print_workflow:
    docker:
      - image: cimg/base:2021.11
    steps:
      - print_pipeline_id

workflows:
  hello-world-workflow:
    jobs:
      # - print-hello
      # - print-world:
      #     requires:
      #       - print-hello
      # - print-env
      # - save_hello_world_output
      # - print_output_file:
      #     requires:
      #       - save_hello_world_output
      - print_workflow
