version: 2.1

jobs:
  print-hello:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Echo Hello
          command: echo hello

  print-world:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run:
          name: Echo World
          command: echo world

  env-practice:
    docker: cimg/base:2021.11
    steps:
      - run:
          name: Echo Env
          command: echo $MY_NAME

workflows:
  hello-world-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
